version: "3"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ip-proxysql:6033
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: rullabcd
      WORDPRESS_DB_PASSWORD: rullabcd
    volumes:
      - ./wp_data:/var/www/html
#      - ./gluster:/var/www/html/wp-content/uploads
