version: "3"
services:
  db1:
    image: mariadb:10.6
    container_name: mariadb-node1
    hostname: db1
    networks:
      - galera-net
    environment:
      - MARIADB_ROOT_PASSWORD=siswa
    volumes:
      - ./galera/node1.cnf:/etc/mysql/conf.d/galera.cnf
      - ./galera/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db1-data:/var/lib/mysql
    command: --wsrep-new-cluster
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db2:
    image: mariadb:10.6
    container_name: mariadb-node2
    hostname: db2
    networks:
      - galera-net
    environment:
      - MARIADB_ROOT_PASSWORD=siswa
    volumes:
      - ./galera/node2.cnf:/etc/mysql/conf.d/galera.cnf
      - db2-data:/var/lib/mysql
    depends_on:
      db1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  db3:
    image: mariadb:10.6
    container_name: mariadb-node3
    hostname: db3
    networks:
      - galera-net
    environment:
      - MARIADB_ROOT_PASSWORD=siswa
    volumes:
      - ./galera/node3.cnf:/etc/mysql/conf.d/galera.cnf
      - db3-data:/var/lib/mysql
    depends_on:
      db2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    hostname: proxysql
    networks:
      - galera-net
    ports:
      - "6032:6032"
      - "6033:6033"
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
      - proxysql-data:/var/lib/proxysql
      - ./proxysql/init.sql:/init.sql
      - ./proxysql/entrypoint.sh:/entrypoint.sh
    entrypoint: ["sh", "/entrypoint.sh"]
    depends_on:
      db3:
        condition: service_healthy

networks:
  galera-net:
    name: galera-net
    external: false

volumes:
  db1-data:
  db2-data:
  db3-data:
  proxysql-data:
